### ISSUE TITLE
Ingress status bug

### ISSUE THREAD

**Issue by bvennam** [knative-sandbox/async-component#38]
Steps to recreate:
1. Create a service
2. Update Knative-serving config map to async.ingress....
3. This causes a new ingress to be created, but the Ready status will not be set to True

**Comment by beemarie** [comment]
ensure this still exists.

**Comment by AngeloDanducci** [comment]
I have a service created (helloworld-sleep) and  updated knative serving to async as follows:
```
kubectl patch configmap/config-network \
-n knative-serving \
--type merge \
-p '{"data":{"ingress.class":"async.ingress.networking.knative.dev"}}'
```
When looking at the list of kingresses seems the helloworld sleep service updates successfully but the async producer and consumer fail to become ready
```
kubebectl get kingress --all-namespaces
NAMESPACE         NAME                   READY   REASON
default           helloworld-sleep       True    
default           helloworld-sleep-new   True    
knative-serving   async-consumer         True    
knative-serving   async-consumer-new     False   DomainConflict
knative-serving   async-producer         True    
knative-serving   async-producer-new     False   DomainConflict
```
Is this what we needed to ensure still exists as per the issue?  

Currently researching `DomainConflict` to gain some better understanding, let me know if you have any pointers on where to look to begin to resolve this @bvennam

**Comment by AngeloDanducci** [comment]
Note to retest this with everything 1.0 just to have a new baseline.

**Comment by AngeloDanducci** [comment]
Using the same testing method as above the outcome is slightly different with 1.0

```
kubectl get kingress --all-namespaces -v
NAMESPACE         NAME                   READY     REASON
default           helloworld-sleep       True      
default           helloworld-sleep-new   True      
knative-serving   async-consumer         True      
knative-serving   async-consumer-new     Unknown   Uninitialized
knative-serving   async-producer         True      
knative-serving   async-producer-new     Unknown   Uninitialized
```

**Comment by maximilien** [comment]
/assign @AngeloDanducci 

Please add short comment on how this was fixed or not reproducible and I will close it. Thx

**Comment by maximilien** [comment]
OK. I see you did add a comment :) my bad.

/close

**Comment by AngeloDanducci** [comment]
Just to add some additional commentary here, this bug seems to be specific to the async-producer / consumer.

The async producer/consumer are using kingresses that get changed along with all  kingresses when the serving configmap gets updated. 

User services get a new host (as intended) while the async producer / consumer should not get a new host but are anyway.

The new host async producer/consumer ingresses are the ones with errors and the E2E still appear to work correctly given the initial setup of async producer / consumer is functional making this cosmetic in nature.

I think the handling of this is done at the networking level so if we want to clean this up / disallow the change to async producer / consumer I am unclear as to how easy that would be or if the change would be desired.
